Use >&2 in each functions

diff --git a/gttrans b/gttrans
--- a/gttrans
+++ b/gttrans
@@ -2,7 +2,7 @@
 set -eu
 
 usage() {
-  cat <<__USAGE__
+  cat <<__USAGE__ >&2
 usage: ${0##*/} <operation> [...]
 operations:"
   ${0##*/} {-h --help}              # show this help message
@@ -12,7 +12,7 @@ __USAGE__
 }
 
 warn() {
-  echo "${0##*/}: $*"
+  echo "${0##*/}: $*" >&2
 }
 
 schema() {
@@ -46,12 +46,12 @@ set_transparency() {
 }
 
 if [ "$#" -lt 1 ]; then
-  usage >&2
+  usage
   exit 2
 fi
 case "$1" in
   -h|-help|--help)
-    usage >&2
+    usage
     exit 0
     ;;
   -g|-get|--get)
@@ -60,14 +60,14 @@ case "$1" in
     ;;
   -s|-set|--set)
     if [ "$#" -lt 2 ]; then
-      warn "no specify percentage" >&2
+      warn "no specify percentage"
       exit 2
     fi
     set_transparency "$2"
     exit 0
     ;;
   *)
-    warn "invalid operation '$1'" >&2
+    warn "invalid operation '$1'"
     exit 2
     ;;
 esac
