Extract warn

diff --git a/gttrans b/gttrans
--- a/gttrans
+++ b/gttrans
@@ -11,6 +11,10 @@ operations:"
 __USAGE__
 }
 
+warn() {
+  echo "${0##*/}: $*"
+}
+
 schema() {
   (
     uuid="$(gsettings get org.gnome.Terminal.ProfilesList default)"
@@ -56,14 +60,14 @@ case "$1" in
     ;;
   -s|-set|--set)
     if [ "$#" -lt 2 ]; then
-      echo "${0##*/}: no specify percentage" >&2
+      warn "no specify percentage" >&2
       exit 2
     fi
     set_transparency "$2"
     exit 0
     ;;
   *)
-    echo "${0##*/}: invalid operation '$1'" >&2
+    warn "invalid operation '$1'" >&2
     exit 2
     ;;
 esac
