Extract main

diff --git a/gttrans b/gttrans
--- a/gttrans
+++ b/gttrans
@@ -8,6 +8,34 @@ uuid="${uuid%%\'}"
 schema="org.gnome.Terminal.Legacy.Profile:"\
 "/org/gnome/terminal/legacy/profiles:/:$uuid/"
 
+main() {
+  if [ "$#" -lt 1 ]; then
+    usage
+    exit 2
+  fi
+  case "$1" in
+    -h|--help)
+      usage
+      exit 0
+      ;;
+    -g|--get)
+      get_transparency
+      exit 0
+      ;;
+    -s|--set)
+      if [ "$#" -lt 2 ]; then
+        echo "$NAME: no specify percentage"
+        exit 2
+      fi
+      set_transparency "$2"
+      exit 0
+      ;;
+    *)
+      echo "$NAME: invalid operation '$1'"
+      exit 2
+      ;;
+  esac
+}
 usage() {
   echo "usage: $NAME <operation> [...]"
   echo "operations:"
@@ -28,29 +56,5 @@ set_transparency() {
   gsettings set "$schema" "background-transparency-percent" "$per"
 }
 
-if [ "$#" -lt 1 ]; then
-  usage
-  exit 2
-fi
-case "$1" in
-  -h|--help)
-    usage
-    exit 0
-    ;;
-  -g|--get)
-    get_transparency
-    exit 0
-    ;;
-  -s|--set)
-    if [ "$#" -lt 2 ]; then
-      echo "$NAME: no specify percentage"
-      exit 2
-    fi
-    set_transparency "$2"
-    exit 0
-    ;;
-  *)
-    echo "$NAME: invalid operation '$1'"
-    exit 2
-    ;;
-esac
+main $*
+exit 0
